### ISSUE TITLE
Blackjack tables not loading or working

### ISSUE THREAD

**Issue by Holidayy95** [qbcore-framework/qb-blackjack#4]
Hello.

I've got MrBrowns CasinoInterior, when I go to the tables no one is there, all the shops works though.

Is there something else I need to change or edit?

**Comment by ihyajb** [comment]
All script about or involving the casino use [dlc-ipl-loader](https://forum.cfx.re/t/cayo-perico-casino-dlc-ipl-loader/2099391)
